CREATE TABLE [dbo].[Attendance]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	Date DATE NOT NULL,
	CheckIn DATETIME NOT NULL,
	CheckOut DATETIME NULL,
	SpentTimeInMin INT NULL DEFAULT 0,
	CONSTRAINT PK_Attendance_Id PRIMARY KEY CLUSTERED(Id),
	CONSTRAINT FK_Attendance_UserId FOREIGN KEY (UserId) REFERENCES dbo.Users(Id)
)
