CREATE TABLE [dbo].[Leaves]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	LeaveTypeId UNIQUEIDENTIFIER NOT NULL,
	DateFrom DATETIME NOT NULL,
	DateTo DATETIME NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	Reason NVARCHAR(MAX) NULL,
	IsApproved BIT NULL,
	CreatedDateTime DATETIME NOT NULL,
	CreatedByUserId UNIQUEIDENTIFIER NOT NULL,  
	UpdatedDateTime DATETIME NULL,
	UpdatedByUserId UNIQUEIDENTIFIER NULL, 
	InActiveDateTime DATETIME NULL,
	CONSTRAINT PK_Leaves_Id PRIMARY KEY CLUSTERED(Id),
	CONSTRAINT FK_Leaves_LeavetypeId FOREIGN KEY (LeaveTypeId) REFERENCES dbo.[LeaveTypes](Id) 
)
