CREATE TABLE [dbo].[Project]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	ProjectName NVARCHAR(100) NOT NULL,
	ClientName NVARCHAR(100) NOT NULL,
	[Priority] INT NOT NULL,
	[Description] NVARCHAR(500) NULL,
	StartDate DATETIME NOT NULL,
	Budget DECIMAL(18,2) NOT NULL,
	TeamId UNIQUEIDENTIFIER NOT NULL,
	[Status] INT NOT NULL,
	[CreatedDateTime] DATETIME NOT NULL, 
    [CreatedByUserId] UNIQUEIDENTIFIER NOT NULL, 
    [UpdatedDateTime] DATETIME  NULL, 
    [UpdatedByUserId] UNIQUEIDENTIFIER  NULL,
	InActiveDateTime DATETIME NULL,
	CONSTRAINT PK_Project_Id PRIMARY KEY CLUSTERED(Id),
	CONSTRAINT FK_Project_TeamId FOREIGN KEY (TeamId) REFERENCES dbo.Team(Id)
)
