CREATE TABLE [dbo].[Tasks]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	TaskName NVARCHAR(MAX) NOT NULL,
	ProjectId UNIQUEIDENTIFIER NOT NULL,
	Description NVARCHAR(500) NULL,
	Priority INT NOT NULL,
	DueDate DateTime NOT NULL,
	CreatedDateTime DATETIME NOT NULL,
    CreatedByUserId UNIQUEIDENTIFIER NOT NULL,  
    UpdatedDateTime DATETIME NULL,
    UpdatedByUserId UNIQUEIDENTIFIER NULL,
    InActiveDateTime DATETIME NULL,
	Status INT NOT NULL DEFAULT 0,
	AssignedTo UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT PK_Tasks_Id PRIMARY KEY CLUSTERED(Id),
	CONSTRAINT FK_Task_ProjectId FOREIGN KEY (ProjectId) REFERENCES dbo.Project(Id)
)
