CREATE TABLE [dbo].[TaskSpentTime]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	TaskId UNIQUEIDENTIFIER NOT NULL,
	Date DATETIME NOT NULL,
	StartTime DateTime NOT NULL,
	EndTime DATETIME NULL,
	SpentTimeInMin INT NULL,
	CreatedDateTime DATETIME NOT NULL,
    CreatedByUserId UNIQUEIDENTIFIER NOT NULL,  
    UpdatedDateTime DATETIME NULL,
    UpdatedByUserId UNIQUEIDENTIFIER NULL,
    InActiveDateTime DATETIME NULL
)
