CREATE TABLE [dbo].[TeamAdmin]
(
	Id UNIQUEIDENTIFIER NOT NULL,
	TeamId UNIQUEIDENTIFIER NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	CreatedDateTime DATETIME NOT NULL,
	CreatedByUserId UNIQUEIDENTIFIER NOT NULL,  
	UpdatedDateTime DATETIME NULL,
	UpdatedByUserId UNIQUEIDENTIFIER NULL,  
	InActiveDateTime DATETIME NULL,
	CONSTRAINT PK_TeamAdmin PRIMARY KEY CLUSTERED (Id),
    CONSTRAINT FK_Team_UserId FOREIGN KEY (UserId) REFERENCES dbo.[Users](Id),
	CONSTRAINT FK_Team_TeamId FOREIGN KEY (TeamId) REFERENCES dbo.[Team](Id)
)
