CREATE TABLE [dbo].[Teammember]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	TeamId UNIQUEIDENTIFIER NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	CreatedDateTime DATETIME NOT NULL,
	CreatedByUserId UNIQUEIDENTIFIER NOT NULL,  
	UpdatedDateTime DATETIME NULL,
	UpdatedByUserId UNIQUEIDENTIFIER NULL,  
	InActiveDateTime DATETIME NULL,
	CONSTRAINT PK_TeamMember PRIMARY KEY CLUSTERED (Id),
	CONSTRAINT FK_TeamId FOREIGN KEY (UserId) REFERENCES dbo.[Users](Id),
	CONSTRAINT FK_UserId FOREIGN KEY (TeamId) REFERENCES dbo.[Team](Id)
)
