CREATE PROCEDURE [dbo].[GetAttendanceData]
(
	@UserId UNIQUEIDENTIFIER = NULL,
	@DateFrom DATETIME = NULL,
	@DateTo DATETIME = NULL
)
AS
BEGIN
	SELECT UserId,Date,
	FORMAT(CAST(SWITCHOFFSET(TODATETIMEOFFSET(CheckIn, '+00:00'),'+05:30')AS DATETIME),'hh:mm tt') AS CheckIn,
	FORMAT(CAST(SWITCHOFFSET(TODATETIMEOFFSET(CheckOut, '+00:00'),'+05:30')AS DATETIME),'hh:mm tt') AS CheckOut,
	CAST(SpentTimeInMin / 60.0 AS DECIMAL(10,2)) AS SpentHours,CAST(SWITCHOFFSET(TODATETIMEOFFSET(CheckIn, '+00:00'),'+05:30')AS DATETIME) AS checkInTime,
	CAST(SWITCHOFFSET(TODATETIMEOFFSET(CheckOut, '+00:00'),'+05:30')AS DATETIME) AS CheckOutTime,
	(SELECT TOP 1 1 FROM Attendance WHERE UserId = @UserId AND CheckIn IS NOT NULL AND CheckOut IS NULL) AS isCheckedIn,
	DATEDIFF(DAY,@DateFrom,@DateTo)+1 AS WorkingDays,
	(SELECT COUNT(DISTINCT DATE) FROM Attendance WHERE UserId = @UserId AND DATE BETWEEN @DateFrom AND @DateTo ) AS PresentDays,
	CAST((SELECT SUM(SpentTimeInMin) FROM Attendance WHERE UserId = @UserId AND Date BETWEEN @DateFrom  AND @DateTo AND CheckOut IS NOT NULL) / 60.0 AS DECIMAL(10,2)) AS TotalHours
	FROM Attendance WHERE CAST(DATE AS DATE) BETWEEN CAST(@DateFrom AS DATE) AND CAST(@DateTo AS DATE) ORDER BY checkInTime desc
END